### PR TITLE
Visual `dump`

### PR DESCRIPTION
**Pull request by MikeInnes**
This acts like Julia’s `dump` function but with a little more flair. Suggestions for better/shorter names are welcome.

### CODE REVIEW

**Comment by pfitzseb** [comment]
LGTM, but I'add something like 
```julia
structure(s::AbstractString) = Row(typeof(s), Text(" "), s)
``` 
because strings are just annoying otherwise.

**Comment by MikeInnes** [comment]
Good call. Generally I'd like to avoid special casing stuff that isn't special cased in the language itself, but strings are probably close enough.

I've just done this for `Base.String` for now; seeing structure could still be useful for custom string types, but we can see how it plays out.

**Comment by pfitzseb** [comment]
Could also have both and show a tree with the string itself in the head and it's fields as children, right?

**Comment by MikeInnes** [comment]
Sorta, but that gets a little weird if you have a multiline string (and therefore a tree in the head of a tree). Doing that could probably work but I've tried to avoid it as it could get ugly/confusing quickly.

**Comment by pfitzseb** [comment]
Ah, fair enough. Didn't think of that.

**Pull request merged**
